# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Queue-Any
version:      0.06
version_from: lib/Thread/Queue/Any.pm
installdirs:  site
requires:
    Storable:                      0
    Thread::Queue:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
